// ============================================================
// CortexPress — Database & App Type Definitions
// ============================================================

// ---- User -------------------------------------------------------
export type UserRole = "author" | "viewer" | "admin";

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  created_at?: string;
}

// ---- Post -------------------------------------------------------
export interface Post {
  id: string;
  title: string;
  body: string;
  image_url: string | null;
  author_id: string;
  summary: string | null; // Generated by AI (Gemini)
  created_at: string;
  updated_at: string;
  // Joined fields (when fetched with author info)
  author?: Pick<User, "id" | "name" | "email">;
  comments?: Comment[];
}

export interface PostFormData {
  title: string;
  body: string;
  image_url?: string;
}

// ---- Comment ----------------------------------------------------
export interface Comment {
  id: string;
  post_id: string;
  user_id: string;
  comment_text: string;
  created_at: string;
  // Joined
  author?: Pick<User, "id" | "name" | "email">;
}

export interface CommentFormData {
  comment_text: string;
}

// ---- Pagination -------------------------------------------------
export interface PaginatedResponse<T> {
  data: T[];
  count: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

// ---- API Responses ----------------------------------------------
export interface ApiResponse<T = void> {
  data?: T;
  error?: string;
}

// ---- Supabase Auth Session Helpers ------------------------------
export interface AuthUser {
  id: string;
  email: string;
  profile: User | null;
}